// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTQxjyCusSYPem5RYI0Dmc-H8L41fzF2o',
    appId: '1:675456233120:web:c5fa7486b4b8bf6d6ea3c5',
    messagingSenderId: '675456233120',
    projectId: 'up-toda',
    authDomain: 'up-toda.firebaseapp.com',
    storageBucket: 'up-toda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmSEIewMasZBz46rj8RpKDGUyqhRRyBT8',
    appId: '1:675456233120:android:2a879e049c9b29c16ea3c5',
    messagingSenderId: '675456233120',
    projectId: 'up-toda',
    storageBucket: 'up-toda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdzbCJJxNZGBIOjESf_MdKOeiIE5HVxqA',
    appId: '1:675456233120:ios:c9d3689345935a3b6ea3c5',
    messagingSenderId: '675456233120',
    projectId: 'up-toda',
    storageBucket: 'up-toda.appspot.com',
    iosBundleId: 'com.example.upTodo',
  );
}
